version: '3.8'

services:
  laravel:
    build:
      context: './vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: gpt-api
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - .:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gptapi.rule=Host(`gpt.e-api.ru`)"
      - "traefik.http.routers.gptapi.entrypoints=web"
      - "traefik.http.services.gptapi.loadbalancer.server.port=80"
    networks:
      - sail
      - traefik
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
      mailpit:
        condition: service_started
      selenium:
        condition: service_started

  mysql:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
    volumes:
      - sail-mysql:/var/lib/mysql
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      retries: 10
      timeout: 5s

  redis:
    image: redis:alpine
    volumes:
      - sail-redis:/data
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    volumes:
      - sail-meilisearch:/meili_data
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--spider", "http://127.0.0.1:7700/health" ]
      retries: 3
      timeout: 5s

  mailpit:
    image: axllent/mailpit:latest
    networks:
      - sail

  selenium:
    image: selenium/standalone-chromium
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - sail

networks:
  sail:
    driver: bridge
  traefik:
    external: true

volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
